#! /bin/sh

sxhkd &
polybar itsbar &
feh --bg-center ~/img/wallpaper.jpg

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width   1
bspc config window_gap     16

bspc config top_padding    16
bspc config left_padding   16
bspc config right_padding  16
bspc config bottom_padding 16

bspc config normal_border_color  #333333
bspc config focused_border_color #e5e5e5

bspc config pointer_modifier mod1
